site_name: Jackal Robot Documentation
site_description: Complete documentation for Clearpath Jackal robots at CRAL-UVA
site_author: CRAL-UVA
repo_url: https://github.com/CRAL-UVA/CRAL-UVA
repo_name: CRAL-UVA/CRAL-UVA

# Set docs_dir to current directory since mkdocs.yml is in the same folder as docs
docs_dir: .

# theme:
#   name: material
#   palette:
#     - scheme: default
#       primary: blue
#       accent: blue
#       toggle:
#         icon: material/brightness-7
#         name: Switch to dark mode
#     - scheme: slate
#       primary: blue
#       accent: blue
#       toggle:
#         icon: material/brightness-4
#         name: Switch to light mode

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - breadcrumbs
    - content.code.copy
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
# extra_css:
#   - stylesheets/readthedocs.css

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
      enable_date_modified: true

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/CRAL-UVA/CRAL-UVA
#     - icon: fontawesome/brands/twitter
#       link: https://x.com/CRAL_UVA

nav:
  - Home: index.md
  - User Manual: Main_files/User_Manual.md
  - Tutorials: Main_files/Tutorials.md
  - Integration: Main_files/Integration.md
  - Maintenance: Main_files/Maintenance.md
  - Troubleshooting: Main_files/Troubleshooting.md
  - Setup:
    - ROS 2 Installation: Setup_files/Ros_installation.md
    - Sensor Drivers: Setup_files/sensor_drivers.md
  - Demos:
    - Demo 1: demos/single_robot_setup.md
    - Demo 2: demos/multi_robot_setup.md
  - Robots:
    - Jackal 93: robots/jackal_93.md
    - Jackal 96: robots/jackal_96.md


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - attr_list
  - md_in_html